pathway_2= ["reproducibility"
,"how_to_troubleshoot"
,"directories_and_file_paths"
,"data_management_basics"
,"bash_command_line_101"
,"bash_command_line_102"
,"bash_conditionals_loops"
,"bash_scripts"
,"git_intro"
,"git_setup_mac_and_linux"
,"git_setup_windows"
,"git_creation_and_tracking"
,"git_history_of_project"
,"genomics_setup"
,"genomics_quality_control"
,"demystifying_containers"
,"docker_101"
]
