pathway_1 = ["reproducibility"
,"how_to_troubleshoot"
,"learning_to_learn"
,"demystifying_geospatial_data"
,"omics_orientation"
,"demystifying_sql"
,"demystifying_machine_learning"
,"demystifying_large_language_models"
,"demystifying_python"
,"demystifying_regular_expressions"
,"citizen_science"
,"demystifying_containers"
,"git_intro"
,"directories_and_file_paths"
,"data_management_basics"
]